/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package monday;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public int multiplyNumbers(int left, int right) {        
        return left * right;
    }
}
