/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample_hw;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.mockito.MockedConstruction;
import org.mockito.Mockito;
import org.mockito.invocation.InvocationOnMock;

import static org.hamcrest.Matchers.hasProperty;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

public class AppTest {

    private static final float EPSILON = 0.01f;

    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
    }

    @Test
    public void appAddShouldReturnWithTheSumOf2Number() {
        final var app = new App();

        final var result = app.add(12, 12);

        assertEquals(24, result); // It returns with 12 + 42 (the value of `k` variable from `App`)
    }

    @ParameterizedTest
    @CsvSource({"1,2,2", "3,4,12", "0,56,0", "0,0,0", "23,0,0", "1,235,235", "11,11,121", "-2,8,-16", "-3,-6,18"})
    public void appMultiplyShouldReturnWithTheProductOf2Number(int a, int b, int expected) {
        final var result = App.multiply(a, b);

        assertEquals(expected, result);
    }

    @ParameterizedTest
    @CsvSource({"4f", "16f", "64f"})
    public void appInvSqrtShouldWorkForSquareNumbers(float n) {
        assertEquals(1.0f / Math.sqrt(n), App.invSqrt(n), EPSILON);
    }

    @ParameterizedTest
    @CsvSource({"5f", "10f", "41f"})
    public void appInvSqrtShouldWorkForNotSquareNumbers(float n) {
        assertEquals(1.0f / Math.sqrt(n), App.invSqrt(n), EPSILON);
    }

    @Test
    public void appInvSqrtShouldWorkWith1() {
        final var result = App.invSqrt(1);

        assertEquals(1, result, EPSILON);
    }

    @Test
    public void appInvSqrtShouldWorkWith0() {
        final var result = App.invSqrt(0);

        assertEquals(0, result, EPSILON);
    }

    @Test
    public void appInvSqrtShouldWorkWithNegative() {
        final var result = App.invSqrt(-1);

        assertEquals(Float.POSITIVE_INFINITY, result, EPSILON);
    }

    @Test
    public void appSetAgeShouldSetMyAgeAlways() {
        final var expected = 24;
        final var appSpy = spy(App.class);

        doAnswer(invocation -> {
            ((App) invocation.getMock()).setAge(expected);
            return null;
        }).when(appSpy).setAge(anyInt());

        doAnswer(InvocationOnMock::callRealMethod).when(appSpy).setAge(expected);

        appSpy.setAge(99);

        assertEquals(expected, appSpy.getAge());
    }

    @Test
    public void appAdvancedBarRandomShouldReturn42() {
        try (MockedConstruction<AppAdvanced.Bar> barMockedConstruction = Mockito.mockConstruction(AppAdvanced.Bar.class,
                (mockBar, context) -> Mockito.when(mockBar.GetRandom()).thenReturn(42))) {
            final var app = new AppAdvanced();

            app.Compute();

            assertEquals(1, barMockedConstruction.constructed().size());

            for (var mockBar : barMockedConstruction.constructed()) {
                verify(mockBar, times(1)).GetRandom();

                assertEquals(42, mockBar.GetRandom());
            }
        }
    }
}
