/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample_hw;

public class App {

    private int k = 42;
    private int age = 0;

    public int add(int a, int b) {
        return a + k;
    }


    public static int multiply(int a, int b) {
        return a * b;
    }

    public static float invSqrt(float x) {
        float xhalf = 0.5f * x;
        int i = Float.floatToIntBits(x);
        i = 0x5f3759df - (i >> 1);
        x = Float.intBitsToFloat(i);
        x *= (1.5f - xhalf * x * x);
        return x;
    }

    public void setAge(int num) {
        age = num;
    }

    public int getAge() {
        return age;
    }
}
