/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package monday;

import org.junit.Test;
import static org.junit.Assert.*;

import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import static org.mockito.Mockito.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void multiplicationWorks() {
        App classUnderTest = new App();
        assertEquals(4, classUnderTest.multiplyNumbers(2, 2));
    }

    @Test public void multiplicationDoesntWorkMock() {
        App classUnderTestMock = mock(App.class);
        when(classUnderTestMock.multiplyNumbers(2, 2)).thenReturn(5);
        assertEquals(4, classUnderTestMock.multiplyNumbers(2, 2));
    }
}
